image: alpine/edge
packages:
  - emacs-nox
  - hugo
  - rsync
sources:
  - https://github.com/erebid/erebid.dev
environment:
  deploy: sam@144.172.83.108
secrets:
  - 721fdf17-b06d-4168-8bc2-c81a6680abae
tasks:
  - md: |
      cd erebid.dev
      make md
  - hugo: |
      cd erebid.dev
      hugo
  - deploy: |
      cd erebid.dev
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avz --delete public/ $deploy:/var/www/erebid.dev
