image: alpine/edge
packages:
  - hugo
  - rsync
sources:
  - https://github.com/samhza/samhza.com
environment:
  deploy: deploy@samhza.com
secrets:
  - 2fc91676-8471-4b2a-8eba-b1a3dd60f405
tasks:
  - build: |
      cd samhza.com
      hugo
  - upload: |
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      cd samhza.com
      rsync -rP public/ $deploy:/var/www/samhza.com
