image: alpine/edge
packages:
  - hugo
  - rsync
sources:
  - https://github.com/samhza/samhza.com
environment:
  deploy: sam@samhza.com
secrets:
  - ebc839e4-6443-4a5d-bb25-605aa2c10b1f
tasks:
  - hugo: |
      cd samhza.com
      hugo
  - deploy: |
      cd samhza.com
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avz --delete public/ $deploy:/var/www/samhza.com
