image: alpine/edge
packages:
  - emacs-nox
  - hugo
  - rsync
sources:
  - https://github.com/erebid/erebid.dev
environment:
  deploy: sam@144.172.83.108
secrets:
  - ebc839e4-6443-4a5d-bb25-605aa2c10b1f
tasks:
  - md: |
      cd erebid.dev
      make md
  - hugo: |
      cd erebid.dev
      hugo
  - deploy: |
      cd erebid.dev
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avz --delete public/ $deploy:/var/www/erebid.dev
