image: alpine/edge
packages:
  - hugo
  - rsync
environment:
  deploy: deploy@samhza.com
secrets:
  - 2fc91676-8471-4b2a-8eba-b1a3dd60f405
tasks:
  - hugo: |
      cd samhza.com
      hugo
  - deploy: |
      cd samhza.com
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avz --delete public/ $deploy:/var/www/samhza.com
