baseURL = "https://erebid.dev/"
languageCode = "en-us"
title = "erebid"
theme = "erebid"
pygmentsUseClasses=true
summaryLength = 2
[permalinks]
   blog = "blog/:year/:title/"
[taxonomies]
	tag = "tags"
[markup.goldmark.renderer]
	unsafe = true
