(require 'package)

(setq package-archives '(("org" . "https://orgmode.org/elpa/")))
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (url (concat (if no-ssl "http" "https") "://melpa.org/packages/")))
  (add-to-list 'package-archives (cons "melpa" url)))
(setq package-user-dir "/tmp/emacs-blog-stuff")
(package-initialize)
;; (package-refresh-contents)
(defvar packages '(ox-hugo))
(dolist (p packages)
  (unless (package-installed-p p)
    (package-install p)))
(defun org-hugo-export-all-wim-to-md ()
  (org-hugo-export-wim-to-md :all-subtrees nil nil :noerror))
